<div class="card-header">
    <i class="fa fa-file"></i> Change Password
</div>
<div class="card-body">
<div class="col-md-6">
    <form action="/admin/users/changepass" method="post">
        <div class="form-group">
            <label for="password">Password</label>
            <input name="password" class="form-control" id="password" type="password" placeholder="Password" required>
        </div>
        <div class="form-group">
            <label for="password_confirm">Confirm Password</label>
            <input name="password_confirm" class="form-control" id="password_confirm" type="password" placeholder="Password" required>
        </div>

        <input class="btn btn-primary btn-block"  type="submit" value="Change Password" />
    </form>
</div>
</div>