<div class="card-header">
    <i class="fa fa-file"></i> Users
</div>
<div class="card-body">

    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Last Logged</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Last Logged</th>
            </tr>
            </tfoot>
            <tbody>
            <?php foreach($users as $user): ?>
                <tr>
                    <td><?= $user['name']; ?></td>
                    <td><?= $user['email']; ?></td>
                    <td><?= $user['last_login']; ?></td>
                </tr>
            <?php endforeach; ?>

            </tbody>
        </table>
    </div>


</div>
