<div class="row">

    <!-- Blog Entries Column -->
    <div class="col-md-8">

        <h1 class="my-4">Posts Archive
        </h1>

        <?php foreach($posts as $post): ?>
            <a href="/post/<?= $post['id']; ?>"></a>

            <div class="card mb-4">
                <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                <div class="card-body">
                    <h2 class="card-title"><?= $post['title']; ?></h2>
                    <p class="card-text"><?= $post['text']; ?></p>
                    <a href="/post/<?= $post['post_id']; ?>" class="btn btn-primary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                    Posted on <?= $post['datepublished']; ?>
                    <a href="/author/<?= $post['author_id']?>"><?= $post['author']; ?></a>
                </div>
            </div>
        <?php endforeach; ?>

    </div>
</div>
<!-- /.row -->