<div class="row">

    <!-- Blog Entries Column -->
    <div class="col-md-8">

        <h1 class="my-4">Posts Archive
        </h1>

        <?php foreach($posts as $post): ?>
            <a href="/post/<?= $post['id']; ?>"></a>

            <div class="card mb-4">
                <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                <div class="card-body">
                    <h2 class="card-title"><?= $post['title']; ?></h2>
                    <p class="card-text"><?= $post['text']; ?></p>
                    <a href="/post/<?= $post['id']; ?>" class="btn btn-primary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                    Posted on <?= $post['datepublished']; ?>
                    <a href="#"><?= $post['author']; ?></a>
                </div>
            </div>
        <?php endforeach; ?>


        <!-- Pagination -->
        <ul class="pagination justify-content-center mb-4">
            <li class="page-item">
                <a class="page-link" href="#">&larr; Older</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#">Newer &rarr;</a>
            </li>
        </ul>

    </div>
</div>
<!-- /.row -->