<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4"><?= $post['title']; ?></h1>

        <!-- Author -->
        <p class="lead">
            by
            <a href="#"><?= $post['author']; ?></a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on <?= $post['datepublished']; ?></p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

        <hr>
        <?= $post['text']; ?>
        <hr>
    </div>

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
                </div>
            </div>
        </div>

    </div>

</div>
<!-- /.row -->