<div class="card-header">
    <i class="fa fa-file"></i> Add new post
</div>
<div class="card-body">
<div class="col-md-6">
    <form action="/admin/posts/add" method="post">
        <div class="form-group">
            <label for="postTitle">Title</label>
            <input name="title" class="form-control" id="postTitle" type="text" placeholder="Enter post title">
        </div>
        <div class="form-group">
            <label for="postText">Text</label>
            <textarea name="text" class="form-control" id="postText" ></textarea>
        </div>

        <input class="btn btn-primary btn-block"  type="submit" value="Add Post" />
    </form>
</div>
</div>
<script>
    tinymce.init({
        selector: 'textarea',
        height: 500,
        theme: 'modern',
        plugins: 'print preview fullpage searchreplace autolink directionality visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists textcolor wordcount imagetools contextmenu colorpicker textpattern help',
        toolbar1: 'formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat',
        image_advtab: true,
        templates: [
            { title: 'Test template 1', content: 'Test 1' },
            { title: 'Test template 2', content: 'Test 2' }
        ],
        content_css: [
            '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
            '//www.tinymce.com/css/codepen.min.css'
        ]
    });
</script>