<div class="card-header">
    <i class="fa fa-file"></i> Posts
</div>
<div class="card-body">


    <?php /** $posts  */ ?>
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>Title</th>
                <th>Text</th>
                <th>Datepublished</th>
                <th>Added By</th>
                <th>Actions</th>
                <th></th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <th>Title</th>
                <th>Text</th>
                <th>Datepublished</th>
                <th>Added By</th>
                <th>Actions</th>
                <th></th>
            </tr>
            </tfoot>
            <tbody>
            <?php foreach($posts as $post): ?>

                <tr>
                    <td><?= $post['title']; ?></td>
                    <td><?= mb_strcut($post['text'], 0, 25); ?> ...</td>
                    <td><?= $post['datepublished']; ?></td>
                    <td><?= $post['author']; ?></td>
                    <td><a href="/admin/posts/delete/<?= $post['post_id']; ?>"><i class="fa fa-trash"></i> </a></td>
                    <td></td>
                </tr>
            <?php endforeach; ?>

            </tbody>
        </table>
    </div>


</div>
